module JackalGame

  module TileConstants
    T_UNEXPLORED = 0

    T_FORT = 3
    T_FORT_ABORIGEN = 4


    T_SLIDE_HORSE = 12
    T_SLIDE_PARACHUTE = 13
    T_SLIDE_GUN = 15
    T_SLIDE_1 = 16
    T_SLIDE_2 = 17
    T_SLIDE_1T = 18
    T_SLIDE_2T = 19
    T_SLIDE_4 = 20
    T_SLIDE_4T = 21
    T_SLIDE_3 = 22
    T_SLIDE_FWD = 23

    T_ROME_1 = 24
    T_ROME_2 = 25
    T_ROME_3 = 26

    T_CROCODILE = 32

    T_COIN_1 = 40
    T_COIN_2 = 41
    T_COIN_3 = 42
    T_COIN_4 = 43
    T_COIN_5 = 44
    T_CHEST = 45

    T_OCEAN = 46
    

    TRANSIT = [T_SLIDE_HORSE, T_SLIDE_PARACHUTE, T_SLIDE_GUN, T_SLIDE_1, T_SLIDE_2, T_SLIDE_1T, T_SLIDE_2T, T_SLIDE_4, T_SLIDE_4T, T_SLIDE_3, T_SLIDE_FWD]
    SHELTERS = [T_FORT, T_FORT_ABORIGEN]
  end

end
